### ISSUE TITLE
feat: NSQ cluster or public network message synchronization

### ISSUE THREAD

**Issue by godcong** [nsqio/nsq#1360] opened 2021-08-13 04:57 UTC
I now have such a demand, and some nsqds are running on public network servers in different countries.
When I publish a message on a certain server, I need to synchronize it to all machines in different regions.
However, nsqlookupd cannot do this.

I want to upgrade nsqlookupd to support these functions.
Or create a new project.
I hope to get some suggestions from you.

**Comment by mreiferson** [comment] 2021-08-13 07:53
dupe of #510

**Closed by mreiferson** 2021-08-13 07:53 UTC
