### ISSUE TITLE
nsqd: depth is misreported by stats endpoint + diskqueue issues

### ISSUE THREAD

**Issue by stephensearles** [nsqio/nsq#693] opened 2015-12-02 02:57 UTC
I'm seeing statistics that suggest nsqd has zero depth:

```
$ curl localhost:4151/stats
nsqd v0.3.5 (built w/go1.4.2)
start_time 2015-12-01T11:59:17-08:00
uptime 6h30m20.37462046s

   [order.updated  ] depth: 0     be-depth: 0     msgs: 4604     e2e%:
      [nsq_to_file              ] depth: 0     be-depth: 0     inflt: 0    def: 0    re-q: 0     timeout: 0     msgs: 4600     e2e%:
        [V2 search1:34663        ] state: 3 inflt: 0    rdy: 28   fin: 35103    re-q: 0        msgs: 35103    connected: 6h29m6s
      [webhooks                 ] depth: 0     be-depth: 0     inflt: 0    def: 0    re-q: 0     timeout: 0     msgs: 9287     e2e%:
        [V2 w3:50891             ] state: 3 inflt: 0    rdy: 0    fin: 133      re-q: 0        msgs: 133      connected: 1h11m13s
        [V2 w4:38682             ] state: 3 inflt: 0    rdy: 0    fin: 151      re-q: 0        msgs: 151      connected: 1h11m9s
        [V2 w1:36117             ] state: 3 inflt: 0    rdy: 1    fin: 1225     re-q: 0        msgs: 1225     connected: 1h13m26s
        [V2 w2:52852             ] state: 3 inflt: 0    rdy: 0    fin: 165      re-q: 0        msgs: 165      connected: 1h11m16s
```

However, looking at `lsof`, it seems like the process has open diskqueue files with quite a bit of old data in them:

nsqd    24924 deploy   42r   REG   252,3 87083130 12705848 /home/deploy/nsqd_data/order.updated:nsq_to_file.diskqueue.000028.dat

The files themselves are fairly old, being last modified in early November. When nsqd was restarted today, we saw some old messages go out, but probably not all of them.

Is there some reason nsqd would open diskqueue files with data in them, but not send all the messages? Or even report them? Our primary consumer always FINs right away, plus we monitor channel depth and haven't seen it grow significantly.

**Comment by stephensearles** [comment] 2015-12-02 22:50
So here's a theory, but first more context (from IRC):

Old server: A. new server B. B's disk is a hot copy of A's. On A, a while back, we saw a bunch of old messages go out unexpectedly, but that was because it was building up messages from a configuration issue that also unexpectedly got resolved. I saw B send out old messages in the same way, but not nearly as many. I see nsqd on B has open file descriptors to these data files, but is reporting 0 depth. My guess is that A sent out messages, but never fully sync'd to disk such that the copied bits would reflect all the messages had actually sent, so when the disk was copied to B, and we started nsqd there, some of the messages went out. Looking at B now, it has those file descriptors open, and looking at the files on disk, I still see old messages in there. A also has those files still, but the modtime on all of them is like Nov 4. On B, the modtime on some of them is Dec 1, but still Nov 4 for many. I can also report that it looks like our consumer processed the message twice.

**Comment by 0x46616c6b** [comment] 2015-12-11 16:31
Same here. The nsqadmin reports correct depth per nsqd and channel, but the /stats endpoint always reports 0.

**Comment by mreiferson** [comment] 2015-12-12 19:54
@0x46616c6b can you provide example output and screenshots?

**Comment by mreiferson** [comment] 2015-12-12 19:55
@stephensearles I know we spoke a bit about this on IRC but your theory seems plausible, but I'm not sure what we can do now, after the fact, to confirm.

Do you think there's anything actionable in what you've discovered that's worth leaving this issue open for?

**Comment by stephensearles** [comment] 2015-12-14 18:52
I haven't had time to look yet, but I want to poke around nsqd's handling of those data files, and see if there's a reasonable opportunity to even defend against this issue. It'd be expensive to try to reproduce the exact scenario I originally saw this in, but it might be reproducible with some open source virtualization stack. Operationally, we're not doing much about this, because it's an easy enough problem to avoid that I'm not sure it warrants much time spent.

So there's action possible, but I'm not sure it's worth it. Whether that leaves this issue open or closed, either way, is fine by me.

**Comment by 0x46616c6b** [comment] 2015-12-14 22:26
@mreiferson i cannot reproduce it in the actual version (0.3.6). so for me the problem doenst exists anymore.

**Comment by mreiferson** [comment] 2016-01-24 17:16
Given the operation-specific nature of this issue and the fact that we don't have anything materially actionable, I think closing makes sense.

We can always reference it for context if we think there are related bugs in the future.

Thanks @stephensearles!

**Closed by mreiferson** 2016-01-24 17:16 UTC
Labels: bug, question
