### ISSUE TITLE
Add raft based storage HA

### ISSUE THREAD

**Issue by andyxning** [nsqio/nsq#1169] opened 2019-07-25 06:06 UTC
I have no idea about how to do this for now. But, it seems that more and more popular distributed storage system is relying on raft. 

Any plan to add this functionality? 

/cc @ploxiln @mreiferson

**Comment by Telavian** [comment] 2020-02-27 19:22
I am sure this is not easy however it unfortunately is a requirement for me.
I have a cluster of machines and HA storage with persistence is a requirement.

Otherwise if a machine were to crash then all the data on it could become lost.
Of course the drive could be replicated somehow however overall that is not a scalable solution for my case.

**Comment by mreiferson** [comment] 2020-06-11 05:09
Dupe of the generic #510 and #625, closing.

Also hi @andyxning!

**Closed by mreiferson** 2020-06-11 05:09 UTC
Labels: feature
