### ISSUE TITLE
"ERROR: failed to decode JSON - Unexpected token in JSON at position 158"

### ISSUE THREAD

**Issue by IEEE756** [nsqio/nsq#889] opened 2017-04-21 00:41 UTC
When I open my nsqadmin control panal and open one of my topic , something appears like "ERROR: failed to decode JSON - Unexpected token in JSON at position 158", please help..

**Comment by ploxiln** [comment] 2017-04-21 01:02
we'll need to see logging output from nsqadmin in order to help figure this out

**Comment by IEEE756** [comment] 2017-04-21 01:16
@ploxiln  Hello, something shows as "

Apr 21 09:14:48 fanqiang nsqadmin: Get http://pangxie:4151/stats?format=json: dial tcp: lookup pangxie on 208.67.222.222:53: no such host
Apr 21 09:14:48 fanqiang nsqadmin: Get http://xiaoqiang:4151/stats?format=json: dial tcp: lookup xiaoqiang on 208.67.222.222:53: no such host
Apr 21 09:14:48 fanqiang nsqadmin: Get http://fanqiang:4151/stats?format=json: dial tcp: lookup fanqiang on 208.67.222.222:53: no such host
Apr 21 09:14:48 fanqiang nsqadmin: Get http://stone04:4151/stats?format=json: dial tcp: lookup stone04 on 208.67.222.222:53: no such host
Apr 21 09:14:48 fanqiang nsqadmin: Get http://zhoulong:4151/stats?format=json: dial tcp: lookup zhoulong on 208.67.222.222:53: no such host
Apr 21 09:14:48 fanqiang nsqadmin: Get http://yanan:4151/stats?format=json: dial tcp: lookup yanan on 208.67.222.222:53: no such host
Apr 21 09:14:48 fanqiang nsqadmin: Get http://zeiwang:4151/stats?format=json: dial tcp: lookup zeiwang on 208.67.222.222:53: no such host
Apr 21 09:14:48 fanqiang nsqadmin: Get http://zhongzong:4151/stats?format=json: dial tcp: lookup zhongzong on 208.67.222.222:53: no such host
Apr 21 09:14:48 fanqiang nsqadmin: [nsqadmin] 2017/04/21 09:14:48.716632 502 GET /api/counter (114.221.16.213:61097) 11.778933ms
Apr 21 09:14:49 fanqiang nsqlookupd: [nsqlookupd] 2017/04/21 09:14:49.649387 CLIENT(104.143.10.181:49572): pinged (last ping 14.999983553s)

"

**Comment by IEEE756** [comment] 2017-04-21 01:17
Apr 21 09:14:48 fanqiang nsqadmin: [nsqadmin] 2017/04/21 09:14:48.716632 **502 GET /api/counter (114.221.16.213:61097)** 11.778933ms

**Comment by ploxiln** [comment] 2017-04-21 01:23
... we'll need to see the lines before that one.

Also, please use a fenced code block when pasting multiple log lines or terminal output or code - see https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by IEEE756** [comment] 2017-04-21 01:39
Hello , 

`Apr 21 09:31:48 fanqiang nsqadmin: [nsqadmin] 2017/04/21 09:31:48.268221 CI: querying nsqd http://zliuyang:4151/stats?format=json
Apr 21 09:31:48 fanqiang nsqadmin: [nsqadmin] 2017/04/21 09:31:48.268248 CI: querying nsqd http://stone04:4151/stats?format=json
Apr 21 09:31:48 fanqiang nsqadmin: [nsqadmin] 2017/04/21 09:31:48.268283 CI: querying nsqd http://zeiwang:4151/stats?format=json
Apr 21 09:31:48 fanqiang nsqadmin: [nsqadmin] 2017/04/21 09:31:48.268291 CI: querying nsqd http://xiaoqiang:4151/stats?format=json
Apr 21 09:31:48 fanqiang nsqadmin: [nsqadmin] 2017/04/21 09:31:48.268306 CI: querying nsqd http://yanan:4151/stats?format=json
Apr 21 09:31:48 fanqiang nsqadmin: [nsqadmin] 2017/04/21 09:31:48.268355 CI: querying nsqd http://zhongzong:4151/stats?format=json
Apr 21 09:31:48 fanqiang nsqadmin: [nsqadmin] 2017/04/21 09:31:48.268363 CI: querying nsqd http://chadao:4151/stats?format=json
Apr 21 09:31:48 fanqiang nsqadmin: [nsqadmin] 2017/04/21 09:31:48.268459 CI: querying nsqd http://zhoulong:4151/stats?format=json
Apr 21 09:31:48 fanqiang nsqadmin: [nsqadmin] 2017/04/21 09:31:48.268485 CI: querying nsqd http://chenrui2:4151/stats?format=json
Apr 21 09:31:48 fanqiang nsqadmin: [nsqadmin] 2017/04/21 09:31:48.268496 CI: querying nsqd http://pangxie:4151/stats?format=json
Apr 21 09:31:48 fanqiang nsqadmin: [nsqadmin] 2017/04/21 09:31:48.268499 CI: querying nsqd http://fanqiang:4151/stats?format=json
Apr 21 09:31:48 fanqiang nsqadmin: [nsqadmin] 2017/04/21 09:31:48.276649 ERROR: failed to get nsqd stats - Failed to query any nsqd: Get http://xiaoqiang:4151/stats?format=json: dial tcp: lookup xiaoqiang on 208.67.222.222:53: no such host
Apr 21 09:31:48 fanqiang nsqadmin: Get http://zliuyang:4151/stats?format=json: dial tcp: lookup zliuyang on 208.67.222.222:53: no such host
Apr 21 09:31:48 fanqiang nsqadmin: Get http://chenrui2:4151/stats?format=json: dial tcp: lookup chenrui2 on 208.67.222.222:53: no such host
Apr 21 09:31:48 fanqiang nsqadmin: Get http://zhongzong:4151/stats?format=json: dial tcp: lookup zhongzong on 208.67.222.222:53: no such host
Apr 21 09:31:48 fanqiang nsqadmin: Get http://zeiwang:4151/stats?format=json: dial tcp: lookup zeiwang on 208.67.222.222:53: no such host
Apr 21 09:31:48 fanqiang nsqadmin: Get http://chadao:4151/stats?format=json: dial tcp: lookup chadao on 208.67.222.222:53: no such host
Apr 21 09:31:48 fanqiang nsqadmin: Get http://yanan:4151/stats?format=json: dial tcp: lookup yanan on 208.67.222.222:53: no such host
Apr 21 09:31:48 fanqiang nsqadmin: Get http://stone04:4151/stats?format=json: dial tcp: lookup stone04 on 208.67.222.222:53: no such host
Apr 21 09:31:48 fanqiang nsqadmin: Get http://zhoulong:4151/stats?format=json: dial tcp: lookup zhoulong on 208.67.222.222:53: no such host
Apr 21 09:31:48 fanqiang nsqadmin: Get http://pangxie:4151/stats?format=json: dial tcp: lookup pangxie on 208.67.222.222:53: no such host
Apr 21 09:31:48 fanqiang nsqadmin: Get http://fanqiang:4151/stats?format=json: dial tcp: lookup fanqiang on 208.67.222.222:53: no such host
Apr 21 09:31:48 fanqiang nsqadmin: [nsqadmin] 2017/04/21 09:31:48.276666 **502 GET /api/counter (114.221.16.213:62513) 9.626874ms**
Apr 21 09:31:48 fanqiang nsqadmin: [nsqadmin] 2017/04/21 09:31:48.429656 200 GET /static/favicon.png (114.221.16.213:62514) 289.159µs`

**Comment by ploxiln** [comment] 2017-04-21 01:50
for fenced code blocks, the "```" needs to be on its own line, like this:

    ```
    Apr 21 09:31:48 fanqiang nsqadmin: [nsqadmin] 2017/04/21 09:31:48.268221 CI: querying nsqd http://zliuyang:4151/stats?format=json
    Apr 21 09:31:48 fanqiang nsqadmin: [nsqadmin] 2017/04/21 09:31:48.268248 CI: querying nsqd http://stone04:4151/stats?format=json
    Apr 21 09:31:48 fanqiang nsqadmin: [nsqadmin] 2017/04/21 09:31:48.268283 CI: querying nsqd http://zeiwang:4151/stats?format=json
    ```

Anyway, the problem is that nsqadmin can't connect to any of your nsqd, because they report the hostname of the server they are running on as the "broadcast address" (to nsqlookupd), but those hostnames are cannot really be resolved by the server running nsqadmin. So you need to run all those nsqd processes with the `--broadcast-address=` option, specifying a hostname or ip address that nsqadmin can connect to. For example, `nsqd --broadcast-address=10.0.2.45 ...` or maybe `nsqd --broadcast-address=zliuyang.sub.domain.tld ...`

**Comment by IEEE756** [comment] 2017-04-21 02:06
It works , you are very professional, very thanks ..

**Closed** 2017-04-21 02:12 UTC
