### ISSUE TITLE
nsqd:At-least-once delivery may not guaranteed when nsqd crashes between diskqueue removes readFile and msg is delivered to client

### ISSUE THREAD

**Issue by DZGodly** [nsqio/nsq#1354] opened 2021-07-31 04:08 UTC
nsq version : v1.2.0

`Topic` would deliver message to `Channel` which is read from BackendQueue.

```go
// nsqd/topic.go:241
func (t *Topic) messagePump() {
        ···
	// main message loop
	for {
		select {
		case msg = <-memoryMsgChan:
		case buf = <-backendChan:
			msg, err = decodeMessage(buf)
			if err != nil {
				t.ctx.nsqd.logf(LOG_ERROR, "failed to decode message - %s", err)
				continue
			}
		···
		}

		for i, channel := range chans {
			chanMsg := msg
			···
			err := channel.PutMessage(chanMsg)
			···
		}
	}
	···
}
```

Prior to that, `diskQueue` may remove this message at moveForward().
```go
github.com/nsqio/go-diskqueue/diskqueue.go:533
func (d *diskQueue) moveForward() {
	···
		fn := d.fileName(oldReadFileNum)
		err := os.Remove(fn)
        ···
}
```

And nsqd may crash before the client receives the message. In this case, message would lost and nsq couldn't guarantee At-least-once delivery.

Am I right? I'm looking forward to getting an answer. Thanks in advance.

**Comment by mreiferson** [comment] 2021-08-13 07:56
dupe of #510

**Closed by mreiferson** 2021-08-13 07:56 UTC
